/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as MiCuentaRouteImport } from './routes/mi-cuenta'
import { Route as ProyectosIndexRouteImport } from './routes/proyectos.index'
import { Route as ProyectosSlugRouteImport } from './routes/proyectos.$slug'
import { Route as ApiPublicDiditWebhookRouteImport } from './routes/api/public/didit-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const MiCuentaRoute = MiCuentaRouteImport.update({
  id: '/mi-cuenta',
  path: '/mi-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIndexRoute = ProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosSlugRoute = ProyectosSlugRouteImport.update({
  id: '/proyectos/$slug',
  path: '/proyectos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiditWebhookRoute = ApiPublicDiditWebhookRouteImport.update({
  id: '/api/public/didit-webhook',
  path: '/api/public/didit-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/proyectos/': typeof ProyectosIndexRoute
  '/api/public/didit-webhook': typeof ApiPublicDiditWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/proyectos': typeof ProyectosIndexRoute
  '/api/public/didit-webhook': typeof ApiPublicDiditWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/proyectos/': typeof ProyectosIndexRoute
  '/api/public/didit-webhook': typeof ApiPublicDiditWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/mi-cuenta'
    | '/proyectos/$slug'
    | '/proyectos/'
    | '/api/public/didit-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/mi-cuenta'
    | '/proyectos/$slug'
    | '/proyectos'
    | '/api/public/didit-webhook'
  id:
    | '__root__'
    | '/'
    | '/compliance'
    | '/mi-cuenta'
    | '/proyectos/$slug'
    | '/proyectos/'
    | '/api/public/didit-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceRoute: typeof ComplianceRoute
  MiCuentaRoute: typeof MiCuentaRoute
  ProyectosSlugRoute: typeof ProyectosSlugRoute
  ProyectosIndexRoute: typeof ProyectosIndexRoute
  ApiPublicDiditWebhookRoute: typeof ApiPublicDiditWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-cuenta': {
      id: '/mi-cuenta'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof MiCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/': {
      id: '/proyectos/'
      path: '/proyectos'
      fullPath: '/proyectos/'
      preLoaderRoute: typeof ProyectosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$slug': {
      id: '/proyectos/$slug'
      path: '/proyectos/$slug'
      fullPath: '/proyectos/$slug'
      preLoaderRoute: typeof ProyectosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/didit-webhook': {
      id: '/api/public/didit-webhook'
      path: '/api/public/didit-webhook'
      fullPath: '/api/public/didit-webhook'
      preLoaderRoute: typeof ApiPublicDiditWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceRoute: ComplianceRoute,
  MiCuentaRoute: MiCuentaRoute,
  ProyectosSlugRoute: ProyectosSlugRoute,
  ProyectosIndexRoute: ProyectosIndexRoute,
  ApiPublicDiditWebhookRoute: ApiPublicDiditWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
